# Generated by Django 3.2.9 on 2021-11-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_cast_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='poster',
            field=models.ImageField(default=0, upload_to='movie/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='video',
            field=models.FileField(default=0, upload_to='movie/videos'),
            preserve_default=False,
        ),
    ]
