# Generated by Django 3.2.9 on 2021-11-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20211108_0726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ('name',), 'verbose_name': 'movie'},
        ),
        migrations.AddField(
            model_name='movies',
            name='actors',
            field=models.ManyToManyField(to='movies.Cast'),
        ),
    ]
