# Generated by Django 3.2.9 on 2021-11-09 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20211109_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='id_number',
        ),
    ]
