# Generated by Django 3.2.9 on 2021-11-09 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_cast_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='id_number',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, to='movies.idnumber'),
            preserve_default=False,
        ),
    ]
